### ISSUE TITLE
feat(integration): Lookup IP address with Crowdsec

### ISSUE THREAD

**Issue by bouddha-fr** [TracecatHQ/tracecat#840]
Here is a modified node adapted to the new requirements. Let me know what you think. A few changes.

```yml
type: action
definition:
  name: search_ip_address
  namespace: tools.crowdsec
  title: Search for an IP address using the CTI CrowdSec API.
  description: Get threat intel report for an IP address from CrowdSec.
  display_group: CrowdSec
  doc_url: https://crowdsecurity.github.io/api_doc/lapi/#/watchers/searchAlerts
  author: bouddha-fr
  secrets:
    - name: crowdsec_cti
      keys:
        - CTI_API_KEY
      optional_keys: null
  expects:
    ip_address:
      type: str
      description: IPv4 or IPv6 address to analyze or scan.
  steps:
    - ref: search_ip_address
      action: core.http_request
      args:
        url: https://cti.api.crowdsec.net/v2/smoke/${{ inputs.ip_address }}
        method: GET
        headers:
          x-api-key: ${{ SECRETS.crowdsec_cti.CTI_API_KEY }}
  returns: ${{ steps.search_ip_address.result }}
```

![Image](https://github.com/user-attachments/assets/efea71f7-1d4f-49fe-af1e-2c2727cc45da)

**Comment by topher-lo** [comment]
A few thoughts:
- Rename `search_ip_address` to `lookup_ip_address`. Reason is in 0.23+ we now differentiate between `analyze_ip_address` (which runs a new scan) from `lookup_ip_address` (which just gets a known report)
- Title is too long: can you keep it under 5 words e.g. Look up IP address. Also please drop the name of the tool from the title.
- Description is good!

**Comment by 0xbbuddha** [comment]
like this ? 

```yml
type: action
definition:
  name: lookup_ip_address
  namespace: tools.crowdsec
  title: Lookup IP address
  description: Get threat intel report for an IP address from CrowdSec.
  display_group: CrowdSec
  doc_url: https://crowdsecurity.github.io/api_doc/lapi/#/watchers/searchAlerts
  author: bouddha-fr
  secrets:
    - name: crowdsec_cti
      keys:
        - CTI_API_KEY
  expects:
    ip_address:
      type: str
      description: IPv4 or IPv6 address to analyze or scan.
  steps:
    - ref: lookup_ip_address
      action: core.http_request
      args:
        url: https://cti.api.crowdsec.net/v2/smoke/${{ inputs.ip_address }}
        method: GET
        headers:
          x-api-key: ${{ SECRETS.crowdsec_cti.CTI_API_KEY }}
  returns: ${{ steps.lookup_ip_address.result }}
```
