### ISSUE TITLE
feat(integration): Lookup threat intel with Anomali ThreatStream

### ISSUE THREAD

**Issue by landonc** [TracecatHQ/tracecat#847]
**Is your feature request related to a problem? Please describe.**
I have a full set of lookup actions for Anomali ThreatStream to contribute.

Includes:
* lookup_domain
* lookup_email
* lookup_file_hash
* lookup_ip_address
* lookup_url

Here's a copy of the lookup_domain, they all follow the same format, just modifications on parameters on the rest call.

```yaml
type: action
definition:
  name: lookup_domain
  namespace: tools.threatstream
  title: Lookup Domain
  description: Search Anomali ThreatStream for reputation of a domain
  display_group: Anomali ThreatStream
  secrets:
    - name: threatstream
      keys:
        - USERNAME
        - API_KEY
  expects:
    domain:
      type: str
      description: Domain to lookup.
  steps:
    - ref: make_request
      action: core.http_request
      args:
        url: https://api.threatstream.com/api/v2/intelligence/
        method: GET
        headers:
          Accept: application/json
          Authorization: apikey ${{ SECRETS.threatstream.USERNAME}}:${{ SECRETS.threatstream.API_KEY }}
        params:
          value: ${{ inputs.domain }}
          type: domain
          status: active
          limit: 0
  returns: ${{ steps.make_request.result.data }}
```

Will also be contributing to the schema def for lookup_email with the following
```yaml
email:
  type: str
  description: Email to lookup.
```
